# Generated by Django 3.1 on 2020-09-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
                'db_table': 'tr_antecedente',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(verbose_name='fecha que se realiza la consulta')),
                ('motivoconsulta', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'db_table': 'tr_consulta',
            },
        ),
        migrations.CreateModel(
            name='Dia_atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_dia', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dia_atencion',
                'verbose_name_plural': 'dia_atenciones',
                'db_table': 'tr_dia_atencion',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'examenes',
                'db_table': 'tr_examen',
            },
        ),
        migrations.CreateModel(
            name='Horario_atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.CharField(max_length=20)),
                ('hora_fin', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'horario_atencion',
                'verbose_name_plural': 'horario_atenciones',
                'db_table': 'tr_horario_atencion',
            },
        ),
        migrations.CreateModel(
            name='Horario_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dia_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.dia_atencion')),
                ('horario_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.horario_atencion')),
            ],
            options={
                'verbose_name': 'horario_medico',
                'verbose_name_plural': 'horario_medicos',
                'db_table': 'horario_medicos',
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=1)),
                ('estado', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
                'db_table': 'tr_medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=13)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'tr_paciente',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=1)),
                ('tipousuario', models.CharField(max_length=200)),
                ('estado', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'tr_usuario',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tratamiento', models.DateField(verbose_name='fecha que se realiza el tratamiento')),
                ('diagnostico', models.CharField(max_length=200)),
                ('procedimiento', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.consulta')),
            ],
            options={
                'verbose_name': 'tratamiento',
                'verbose_name_plural': 'tratamientos',
                'db_table': 'tr_tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha que ingresa al sistema')),
                ('fecha_reservacion', models.DateField(verbose_name='fecha que se realiza la reservacion')),
                ('estado_reservacion', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.horario_medico')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.usuario')),
            ],
            options={
                'verbose_name': 'reservacion',
                'verbose_name_plural': 'reservaciones',
                'db_table': 'tr_reservaciones',
            },
        ),
        migrations.AddField(
            model_name='horario_medico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
        migrations.CreateModel(
            name='Examen_consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.consulta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.examen')),
            ],
            options={
                'verbose_name': 'examen_consulta',
                'verbose_name_plural': 'examen_consultas',
                'db_table': 'tr_examen_consulta',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.paciente'),
        ),
    ]
