# Generated by Django 3.1 on 2020-09-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen_consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.consulta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.examen')),
            ],
            options={
                'verbose_name': 'examen_consulta',
                'verbose_name_plural': 'examen_consultas',
                'db_table': 'tr_examen_consulta',
            },
        ),
    ]
